### ISSUE TITLE
Latest udiskie community package on Arch Linux is not working 

### ISSUE THREAD

**Issue by elwin1234** [coldfix/udiskie#105]
Hi, 

I used udiskie with pleasure for quite some time, but it has been broken (at least on my system) since quite a while now.

I installed from package mngr on Arch (sudo pacman -S udiskie) and receive the following error when executing a "udiskie" command on terminal:

```
The 'udiskie==1.4.8' distribution was not found and is required by the application
```

Trace:
```
Traceback (most recent call last):
  File "/usr/bin/udiskie", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2912, in <module>
    @_call_aside
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2898, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2925, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 642, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 943, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 830, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'udiskie==1.4.8' distribution was not found and is required by the application
```

**Comment by coldfix** [comment]
Hey, sorry to hear your trouble and thanks for taking the effort to report. On my system the official archlinux package runs fine.

The official package installs as udiskie as python3.5 package while your output shows python2.7 running. Maybe there are some leftovers from a previous udiskie installation on 2.7? Or maybe your system default python is configured to be 2.7?

Try to completely remove udiskie and then reinstall:

```
sudo pacman -Rcns udiskie
sudo pip2 uninstall udiskie
```

If that doesn't help, please post the result of the following commands:

```
cat /usr/bin/udiskie

which python
```

Best regards,
Thomas

**Comment by elwin1234** [comment]
Thanks for your reaction! Python3 vs python2 was indeed my problem. I switched the default to 3 again and now everything works fine.
