### ISSUE TITLE
Replacing udisks with udisks2 causes crash

### ISSUE THREAD

**Issue by jasonwryan** [coldfix/udiskie#132]
Arch has dropped official support for udisks1 in favour of the actively developed udisks2. Replacing udisks1 with udisks2 and then trying to restart udiskie throws this error:

```
 udiskie -Nq                                                                                                                                               
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/udiskie/cli.py", line 288, in _start_async_tasks
    self.udisks = yield get_backend(self.options['udisks_version'])
  File "/usr/lib/python3.6/site-packages/udiskie/async_.py", line 293, in _interact
    value = func(*args)
  File "/usr/lib/python3.6/site-packages/udiskie/cli.py", line 62, in get_backend
    daemon = yield udiskie.udisks1.Daemon.create()
  File "/usr/lib/python3.6/site-packages/udiskie/async_.py", line 293, in _interact
    value = func(*args)
  File "/usr/lib/python3.6/site-packages/udiskie/udisks1.py", line 527, in create
    yield udisks._sync()
  File "/usr/lib/python3.6/site-packages/udiskie/async_.py", line 293, in _interact
    value = func(*args)
  File "/usr/lib/python3.6/site-packages/udiskie/udisks1.py", line 698, in _sync
    object_pathes = yield self._proxy.call('EnumerateDevices', '()')
  File "/usr/lib/python3.6/site-packages/udiskie/dbus.py", line 102, in _callback
    value = proxy.call_finish(result)
GLib.GError: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UDisks was not provided by any .service files (2)
```

Have I missed something?

**Comment by coldfix** [comment]
Did you specify to use udisks1 in your config file `~/.config/udiskie/config.yml`?

**Comment by jasonwryan** [comment]
Yes I did: because I am an idiot.

Sorry for the noise :(

**Comment by coldfix** [comment]
np:)
