### ISSUE TITLE
TypeError: __call__() missing 1 required positional argument: 'extended'

### ISSUE THREAD

**Issue by IvanMalison** [coldfix/udiskie#156]
/usr/local/var/pyenv/versions/3.5.1/lib/python3.5/site-packages/udiskie/appindicator.py:6: PyGIWarning: AppIndicator3 was imported without specifying a version first. Use gi.require_version('AppIndicator3', '0.1') before import to ensure that the right version gets loaded.
  from gi.repository import AppIndicator3
Traceback (most recent call last):
  File "/usr/local/var/pyenv/versions/3.5.1/lib/python3.5/site-packages/udiskie/cli.py", line 307, in _start_async_tasks
    results = yield self._init()
  File "/usr/local/var/pyenv/versions/3.5.1/lib/python3.5/site-packages/udiskie/cli.py", line 492, in _init
    self.statusicon.activate()
  File "/usr/local/var/pyenv/versions/3.5.1/lib/python3.5/site-packages/udiskie/cli.py", line 329, in activate
    self.instance = self.create()
  File "/usr/local/var/pyenv/versions/3.5.1/lib/python3.5/site-packages/udiskie/cli.py", line 549, in _load_statusicon
    trayicon = TrayIcon(menu_maker, icons)
  File "/usr/local/var/pyenv/versions/3.5.1/lib/python3.5/site-packages/udiskie/appindicator.py", line 36, in __init__
    self._maker(self._menu)
TypeError: __call__() missing 1 required positional argument: 'extended'

**Comment by coldfix** [comment]
Hi, I'm not surprised appindicator doesn't work at the moment. I haven't bother with this module in a long time and I can't promise that I will get to fix issues anytime soon either (I have lots of other things to do). I'll inform you when I have time to fix the issue. (meanwhile anyone else is of course welcome to fix this)

Best, Thomas
