### ISSUE TITLE
Async not defined in cli:

### ISSUE THREAD

**Issue by LocutusOfBorg** [coldfix/udiskie#160]
Bug reported in Debian: http://bugs.debian.org/899419

```
$ udiskie -v
DEBUG [2018-05-24 01:28:47,151] udiskie.config: Failed to read config file: [Errno 2] No such file or directory: '/home/vagrant/.config/udiskie/config.yml'
DEBUG [2018-05-24 01:28:47,155] udiskie.config: Failed to read config file: [Errno 2] No such file or directory: '/home/vagrant/.config/udiskie/config.json'
DEBUG [2018-05-24 01:28:47,162] udiskie.udisks2: Daemon version: 2.7.6
DEBUG [2018-05-24 01:28:47,163] udiskie.udisks2: Keyfile support: True
DEBUG [2018-05-24 01:28:47,174] udiskie.config: IgnoreDevice(match={'symlinks': '/dev/mapper/docker-*'}, value={'ignore': True}) created
DEBUG [2018-05-24 01:28:47,175] udiskie.config: IgnoreDevice(match={'symlinks': '/dev/disk/by-id/dm-name-docker-*'}, value={'ignore': True}) created
DEBUG [2018-05-24 01:28:47,175] udiskie.config: IgnoreDevice(match={'is_loop': True, 'loop_file': '/*'}, value={'ignore': False}) created
DEBUG [2018-05-24 01:28:47,176] udiskie.config: IgnoreDevice(match={'is_block': False}, value={'ignore': True}) created
DEBUG [2018-05-24 01:28:47,176] udiskie.config: IgnoreDevice(match={'is_external': False}, value={'ignore': True}) created
DEBUG [2018-05-24 01:28:47,177] udiskie.config: IgnoreDevice(match={'is_ignored': True}, value={'ignore': True}) created
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/udiskie/cli.py", line 307, in _start_async_tasks
    results = yield self._init()
  File "/usr/lib/python3/dist-packages/udiskie/cli.py", line 495, in _init
    tasks.append(Async())
NameError: name 'Async' is not defined
```

**Comment by coldfix** [comment]
Hi, thanks!

Fixed in 1.7.5 (today)

Best, Thomas
