### ISSUE TITLE
cannot start. No module named 'udiskie'

### ISSUE THREAD

**Issue by luntik2012** [coldfix/udiskie#162]
Traceback (most recent call last):
  File "/usr/bin/udiskie", line 6, in <module>
    from udiskie.cli import Daemon
ModuleNotFoundError: No module named 'udiskie'

archlinux

**Comment by coldfix** [comment]
Hi,

how did you install udiskie? (I'm having no problem with the official archlinux package).

What is the output of `which udiskie` and `cat $(which udiskie)`?

Best, Thomas

**Comment by luntik2012** [comment]
> how did you install udiskie? (I'm having no problem with the official archlinux package).
> File "/usr/bin/udiskie", line 6, in 

Installed from archlinux repo using pacman

**Comment by coldfix** [comment]
Still:

- `cat /usr/bin/udiskie`?
- `python --version`
- `pacman -Ql udiskie`

My initial thought was that it might have something to do with the recent migration to py37, e.g. if you did not yet upgrade to py37 but use the latest udiskie package which was updated for 37 already.

**Comment by luntik2012** [comment]
```sh
nick ~ $ cat /usr/bin/udiskie
#!/usr/bin/python
# -*- coding: utf-8 -*-
import re
import sys

from udiskie.cli import Daemon

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(Daemnick ~ $ )​​​​​​​​​​
nick ~ $ python --version
Python 3.7.0
nick ~ $ pacman -Ql udiskie 
udiskie /usr/
udiskie /usr/bin/
udiskie /usr/bin/udiskie
udiskie /usr/bin/udiskie-info
udiskie /usr/bin/udiskie-mount
udiskie /usr/bin/udiskie-umount
udiskie /usr/lib/
udiskie /usr/lib/python3.7/
udiskie /usr/lib/python3.7/site-packages/
udiskie /usr/lib/python3.7/site-packages/udiskie-1.7.5-py3.7.egg-info/
udiskie /usr/lib/python3.7/site-packages/udiskie-1.7.5-py3.7.egg-info/PKG-INFO
udiskie /usr/lib/python3.7/site-packages/udiskie-1.7.5-py3.7.egg-info/SOURCES.txt
udiskie /usr/lib/python3.7/site-packages/udiskie-1.7.5-py3.7.egg-info/dependency_links.txt
udiskie /usr/lib/python3.7/site-packages/udiskie-1.7.5-py3.7.egg-info/entry_points.txt
udiskie /usr/lib/python3.7/site-packages/udiskie-1.7.5-py3.7.egg-info/requires.txt
udiskie /usr/lib/python3.7/site-packages/udiskie-1.7.5-py3.7.egg-info/top_level.txt
udiskie /usr/lib/python3.7/site-packages/udiskie/
udiskie /usr/lib/python3.7/site-packages/udiskie/__init__.py
udiskie /usr/lib/python3.7/site-packages/udiskie/__pycache__/
udiskie /usr/lib/python3.7/site-packages/udiskie/__pycache__/__init__.cpython-37.opt-1.pyc
udiskie /usr/lib/python3.7/site-packages/udiskie/__pycache__/__init__.cpython-37.pyc
udiskie /usr/lib/python3.7/site-packages/udiskie/__pycache__/appindicator.cpython-37.opt-1.pyc
udiskie /usr/lib/python3.7/site-packages/udiskie/__pycache__/appindicator.cpython-37.pyc
udiskie /usr/lib/python3.7/site-packages/udiskie/__pycache__/async_.cpython-37.opt-1.pyc
udiskie /usr/lib/python3.7/site-packages/udiskie/__pycache__/async_.cpython-37.pyc
udiskie /usr/lib/python3.7/site-packages/udiskie/__pycache__/automount.cpython-37.opt-1.pyc
udiskie /usr/lib/python3.7/site-packages/udiskie/__pycache__/automount.cpython-37.pyc
udiskie /usr/lib/python3.7/site-packages/udiskie/__pycache__/cache.cpython-37.opt-1.pyc
udiskie /usr/lib/python3.7/site-packages/udiskie/__pycache__/cache.cpython-37.pyc
udiskie /usr/lib/python3.7/site-packages/udiskie/__pycache__/cli.cpython-37.opt-1.pyc
udiskie /usr/lib/python3.7/site-packages/udiskie/__pycache__/cli.cpython-37.pyc
udiskie /usr/lib/python3.7/site-packages/udiskie/__pycache__/common.cpython-37.opt-1.pyc
udiskie /usr/lib/python3.7/site-packages/udiskie/__pycache__/common.cpython-37.pyc
udiskie /usr/lib/python3.7/site-packages/udiskie/__pycache__/compat.cpython-37.opt-1.pyc
udiskie /usr/lib/python3.7/site-packages/udiskie/__pycache__/compat.cpython-37.pyc
udiskie /usr/lib/python3.7/site-packages/udiskie/__pycache__/config.cpython-37.opt-1.pyc
udiskie /usr/lib/python3.7/site-packages/udiskie/__pycache__/config.cpython-37.pyc
udiskie /usr/lib/python3.7/site-packages/udiskie/__pycache__/dbus.cpython-37.opt-1.pyc
udiskie /usr/lib/python3.7/site-packages/udiskie/__pycache__/dbus.cpython-37.pyc
udiskie /usr/lib/python3.7/site-packages/udiskie/__pycache__/depend.cpython-37.opt-1.pyc
udiskie /usr/lib/python3.7/site-packages/udiskie/__pycache__/depend.cpython-37.pyc
udiskie /usr/lib/python3.7/site-packages/udiskie/__pycache__/locale.cpython-37.opt-1.pyc
udiskie /usr/lib/python3.7/site-packages/udiskie/__pycache__/locale.cpython-37.pyc
udiskie /usr/lib/python3.7/site-packages/udiskie/__pycache__/mount.cpython-37.opt-1.pyc
udiskie /usr/lib/python3.7/site-packages/udiskie/__pycache__/mount.cpython-37.pyc
udiskie /usr/lib/python3.7/site-packages/udiskie/__pycache__/notify.cpython-37.opt-1.pyc
udiskie /usr/lib/python3.7/site-packages/udiskie/__pycache__/notify.cpython-37.pyc
udiskie /usr/lib/python3.7/site-packages/udiskie/__pycache__/prompt.cpython-37.opt-1.pyc
udiskie /usr/lib/python3.7/site-packages/udiskie/__pycache__/prompt.cpython-37.pyc
udiskie /usr/lib/python3.7/site-packages/udiskie/__pycache__/tray.cpython-37.opt-1.pyc
udiskie /usr/lib/python3.7/site-packages/udiskie/__pycache__/tray.cpython-37.pyc
udiskie /usr/lib/python3.7/site-packages/udiskie/__pycache__/udisks1.cpython-37.opt-1.pyc
udiskie /usr/lib/python3.7/site-packages/udiskie/__pycache__/udisks1.cpython-37.pyc
udiskie /usr/lib/python3.7/site-packages/udiskie/__pycache__/udisks2.cpython-37.opt-1.pyc
udiskie /usr/lib/python3.7/site-packages/udiskie/__pycache__/udisks2.cpython-37.pyc
udiskie /usr/lib/python3.7/site-packages/udiskie/appindicator.py
udiskie /usr/lib/python3.7/site-packages/udiskie/async_.py
udiskie /usr/lib/python3.7/site-packages/udiskie/automount.py
udiskie /usr/lib/python3.7/site-packages/udiskie/cache.py
udiskie /usr/lib/python3.7/site-packages/udiskie/cli.py
udiskie /usr/lib/python3.7/site-packages/udiskie/common.py
udiskie /usr/lib/python3.7/site-packages/udiskie/compat.py
udiskie /usr/lib/python3.7/site-packages/udiskie/config.py
udiskie /usr/lib/python3.7/site-packages/udiskie/dbus.py
udiskie /usr/lib/python3.7/site-packages/udiskie/depend.py
udiskie /usr/lib/python3.7/site-packages/udiskie/locale.py
udiskie /usr/lib/python3.7/site-packages/udiskie/mount.py
udiskie /usr/lib/python3.7/site-packages/udiskie/notify.py
udiskie /usr/lib/python3.7/site-packages/udiskie/prompt.py
udiskie /usr/lib/python3.7/site-packages/udiskie/tray.py
udiskie /usr/lib/python3.7/site-packages/udiskie/udisks1.py
udiskie /usr/lib/python3.7/site-packages/udiskie/udisks2.py
udiskie /usr/share/
udiskie /usr/share/icons/
udiskie /usr/share/icons/hicolor/
udiskie /usr/share/icons/hicolor/scalable/
udiskie /usr/share/icons/hicolor/scalable/actions/
udiskie /usr/share/icons/hicolor/scalable/actions/udiskie-detach.svg
udiskie /usr/share/icons/hicolor/scalable/actions/udiskie-eject.svg
udiskie /usr/share/icons/hicolor/scalable/actions/udiskie-lock.svg
udiskie /usr/share/icons/hicolor/scalable/actions/udiskie-mount.svg
udiskie /usr/share/icons/hicolor/scalable/actions/udiskie-unlock.svg
udiskie /usr/share/icons/hicolor/scalable/actions/udiskie-unmount.svg
udiskie /usr/share/licenses/
udiskie /usr/share/licenses/udiskie/
udiskie /usr/share/licenses/udiskie/LICENSE
udiskie /usr/share/locale/
udiskie /usr/share/locale/en_US/
udiskie /usr/share/locale/en_US/LC_MESSAGES/
udiskie /usr/share/locale/en_US/LC_MESSAGES/udiskie.mo
udiskie /usr/share/locale/es_ES/
udiskie /usr/share/locale/es_ES/LC_MESSAGES/
udiskie /usr/share/locale/es_ES/LC_MESSAGES/udiskie.mo
udiskie /usr/share/man/
udiskie /usr/share/man/man8/
udiskie /usr/share/man/man8/udiskie.8.gz
udiskie /usr/share/zsh/
udiskie /usr/share/zsh/site-functions/
udiskie /usr/share/zsh/site-functions/_udiskie
udiskie /usr/share/zsh/site-functions/_udiskie-mount
udiskie /usr/share/zsh/site-functions/_udiskie-umount
```

**Comment by luntik2012** [comment]
it works now btw O_o
