### ISSUE TITLE
Handle missing device more gracefully

### ISSUE THREAD

**Issue by coldfix** [coldfix/udiskie#179]
Calling `udiskie-info` with an invalid device (and other valid ones), no info is printed and an exception traceback is shown instead:

> However, it breaks when when searching for /dev/loop
> 
> ```
> myuser@mycomputer:~$ udiskie-info -o 'id_type' /dev/loop*
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/udiskie/cli.py", line 289, in _start_async_tasks
>     results = yield self._init()
>   File "/usr/lib/python3/dist-packages/udiskie/cli.py", line 724, in _init
>     devices = [self.udisks.find(path) for path in options['<device>']]
>   File "/usr/lib/python3/dist-packages/udiskie/cli.py", line 724, in <listcomp>
>     devices = [self.udisks.find(path) for path in options['<device>']]
>   File "/usr/lib/python3/dist-packages/udiskie/udisks2.py", line 584, in find
>     raise ValueError(_('no device found owning "{0}"', path))
> ValueError: master device was not found for "/dev/loop-control"
> ```

_Originally posted by @mixpc in https://github.com/coldfix/udiskie/issues/177#issuecomment-488626200_

This should be handled more gracefully, show a "invalid device: {...}" message on stderr, but print the rest of the information nevertheless.

Opening this here as separate issue so I don't forget about it.

**Comment by hohol92** [comment]
I think this is not a problem
