### ISSUE TITLE
Error when trying to open

### ISSUE THREAD

**Issue by hrqmonteiro** [coldfix/udiskie#212]
I'm on void, i installed it via `xbps-install udiskie`

And it returns me this:

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/udiskie/cli.py", line 222, in _start_async_tasks
    self.udisks = await udiskie.udisks2.Daemon.create()
  File "/usr/lib/python3.9/site-packages/udiskie/udisks2.py", line 699, in create
    proxy = await dbus.connect_service(*service)
  File "/usr/lib/python3.9/site-packages/udiskie/dbus.py", line 288, in connect_service
    proxy = await proxy_new_for_bus(
  File "/usr/lib/python3.9/site-packages/udiskie/dbus.py", line 280, in proxy_new_for_bus
    value = Gio.DBusProxy.new_for_bus_finish(result)
gi.repository.GLib.GError: g-io-error-quark: Could not connect: No such file or directory (1)
```

**Comment by coldfix** [comment]
Hi,

thanks for taking the time to report.

Looks like a more general issue with dbus or udisks. Did you try turning it off and on again? 😄 

Does any of these resources help:

- https://unix.stackexchange.com/questions/254036/g-io-error-quark-39-error-when-stopping-dbus-service (happens after some update)
- https://access.redhat.com/solutions/3522441 (system has `/var` on separate partition)
- https://www.linuxhelp.com/questions/error-getting-authority-error-initializing-authority-could-not-connect-no-such-file-or-directory-g-io-error-quark-1 (`/etc/fstab` contains an entry that is no longer valid)
