### ISSUE TITLE
python messages about dbus.py and udisks2.py

### ISSUE THREAD

**Issue by 13di31** [coldfix/udiskie#272]
When I issue the comand "udiskie-umount -d _mountpoint_" it gives me:
```
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/udiskie/dbus.py", line 225, in callback
    return handler(object_path, *unpack_variant(parameters))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/udiskie/udisks2.py", line 865, in _properties_changed
    del self._objects[object_path][interface_name][property_name]
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'Size'
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/udiskie/dbus.py", line 225, in callback
    return handler(object_path, *unpack_variant(parameters))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/udiskie/udisks2.py", line 865, in _properties_changed
    del self._objects[object_path][interface_name][property_name]
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'Size'
unmounted /org/freedesktop/UDisks2/block_devices/sdc1
detached /org/freedesktop/UDisks2/block_devices/sdc1
```
and it does the job (ie. the device is unmounted and powered off).

I'm with udiskie version 2.4.2 on Arch (updated yesterday). Udiskie is lauched when i log in with "udiskie -aNT &" by i3-wm.

**Comment by brett** [comment]
+1 same here

**Comment by emilyyyylime** [comment]
I am also facing this, seemingly with mounting rather than unmounting however. My instance is also launched automatically in my sway config, with `--tray`

**Comment by coldfix** [comment]
Thanks for reporting. Should be easy to fix.

**Comment by JostBrand** [comment]
Reopening since this error is not actually fixed. Running version 2.5.1.1. Mounting and unmounting works flawless but still this message persists.

Running  udiskie &  without any configuration.

 

```
Traceback (most recent call last):         ✘ IOT  46m 34s  12:58:33 PM
  File "/home/jost/.local/lib/python3.11/site-packages/udiskie/dbus.py", line 225, in callback
    return handler(object_path, *unpack_variant(parameters))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jost/.local/lib/python3.11/site-packages/udiskie/udisks2.py", line
865, in _properties_changed
    del self._objects[object_path][interface_name][property_name]
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'Size'
Traceback (most recent call last):
  File "/home/jost/.local/lib/python3.11/site-packages/udiskie/dbus.py", line 225, in callback
    return handler(object_path, *unpack_variant(parameters))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jost/.local/lib/python3.11/site-packages/udiskie/udisks2.py", line
865, in _properties_changed
    del self._objects[object_path][interface_name][property_name]
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'Size'
mounted /org/freedesktop/UDisks2/block_devices/sde1 on /run/media/jost/9970ace7-367e-42bc-b65c-f8000967f295
```

**Comment by coldfix** [comment]
Hi @JostBrand. Is it possible that you are still somehow running an old version (local user pip install or something)? Did you do `udiskie --version`?

**Comment by JostBrand** [comment]
you are right ! I think I played with the dangerous break system packages and my shell preferred the pip install over the pacman version. 

Sorry!
