### ISSUE TITLE
Install error with recent setuptools

### ISSUE THREAD

**Issue by bubbleguuum** [coldfix/udiskie#297]
With latest  `setuptools` 75.6.0, install fails with:

```
[    4s] Traceback (most recent call last):
[    4s]   File "/home/abuild/rpmbuild/BUILD/udiskie-2.5.3/setup.py", line 98, in <module>
[    4s]     setup(
[    4s]   File "/usr/lib/python3.11/site-packages/setuptools/__init__.py", line 117, in setup
[    4s]     return distutils.core.setup(**attrs)
[    4s]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[    4s]   File "/usr/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 183, in setup
[    4s]     return run_commands(dist)
[    4s]            ^^^^^^^^^^^^^^^^^^
[    4s]   File "/usr/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 199, in run_commands
[    4s]     dist.run_commands()
[    4s]   File "/usr/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 954, in run_commands
[    4s]     self.run_command(cmd)
[    4s]   File "/usr/lib/python3.11/site-packages/setuptools/dist.py", line 995, in run_command
[    4s]     super().run_command(command)
[    4s]   File "/usr/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
[    4s]     cmd_obj.run()
[    4s]   File "/usr/lib/python3.11/site-packages/setuptools/command/install.py", line 103, in run
[    4s]     return super().run()
[    4s]            ^^^^^^^^^^^^^
[    4s]   File "/usr/lib/python3.11/site-packages/setuptools/_distutils/command/install.py", line 706, in run
[    4s]     self.run_command(cmd_name)
[    4s]   File "/usr/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
[    4s]     self.distribution.run_command(command)
[    4s]   File "/usr/lib/python3.11/site-packages/setuptools/dist.py", line 995, in run_command
[    4s]     super().run_command(command)
[    4s]   File "/usr/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
[    4s]     cmd_obj.run()
[    4s]   File "/usr/lib/python3.11/site-packages/setuptools/command/install_scripts.py", line 31, in run
[    4s]     self._install_ep_scripts()
[    4s]   File "/usr/lib/python3.11/site-packages/setuptools/command/install_scripts.py", line 56, in _install_ep_scripts
[    4s]     for args in writer.get_args(dist, cmd.as_header()):
[    4s]   File "/usr/lib/python3.11/site-packages/setuptools/command/easy_install.py", line 2169, in get_args
[    4s]     script_text = cls.template % locals()
[    4s]                   ~~~~~~~~~~~~~^~~~~~~~~~
[    4s]   File "/home/abuild/rpmbuild/BUILD/udiskie-2.5.3/setup.py", line 91, in __mod__
[    4s]     func = '.'.join(context['ep'].attrs)
[    4s]                     ~~~~~~~^^^^^^
[    4s] KeyError: 'ep'
```

Commenting this line in `setup.py` seems to workaround it, but I am not certain it is 100% correct:

```
#ScriptWriter.template = fast_entrypoint_script_template()
```

**Comment by coldfix** [comment]
Hi,

thanks for the heads up! I will probably just remove this part. As far as I can remember, it is only useful for installing with setuptools directly (`python setup.py install`) which is not the preferred installation mode anyway.

**Comment by bubbleguuum** [comment]
I noticed this issue when the udiskie openSUSE TW package did not install. It uses `python setup.py install` to do so, via a rpm macro `%python3_install`.
 I just commented the `ScriptWriter.template` line and it seems to install fine without side effect that I could tell.
