### ISSUE TITLE
the package doesn't build in a pbuilder environment (like Debian and Ubuntu buildds)

### ISSUE THREAD

**Issue by LocutusOfBorg** [coldfix/udiskie#68]
This is the full build log [1]
and the snip of the log
```

dh_auto_clean
I: pybuild base:170: python2.7 setup.py clean 
gdk_mir_display_open
Failed to connect to Mir: Failed to connect to server socket: No such file or directory
Unable to init server: Could not connect: Connection refused
running clean
removing '/build/buildd/python-udiskie-1.2.0/.pybuild/pythonX.Y_2.7/build' (and everything under it)
'build/bdist.linux-x86_64' does not exist -- can't clean it
'build/scripts-2.7' does not exist -- can't clean it
I: pybuild base:170: python3.4 setup.py clean 
gdk_mir_display_open
Failed to connect to Mir: Failed to connect to server socket: No such file or directory
Unable to init server: Could not connect: Connection refused
Traceback (most recent call last):
  File "setup.py", line 51, in <module>
    metadata = exec_file('udiskie/__init__.py')
  File "setup.py", line 48, in exec_file
    exec(f.read(), namespace, namespace)
  File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 307: ordinal not in range(128)
E: pybuild pybuild:256: clean: plugin distutils failed with: exit code=1: python3.4 setup.py clean 
dh_auto_clean: pybuild --clean -i python{version} -p 3.4 --dir . returned exit code 13
debian/rules:9: recipe for target 'override_dh_auto_clean' failed
make[1]: *** [override_dh_auto_clean] Error 13
make[1]: Leaving directory '/build/buildd/python-udiskie-1.2.0'
debian/rules:6: recipe for target 'clean' failed
```

[1]  https://launchpadlibrarian.net/209762733/buildlog_ubuntu-wily-amd64.python-udiskie_1.2.0-1_BUILDING.txt.gz

**Comment by coldfix** [comment]
Hi, can you check out the branch `fix-unicode-setup-issue` and see if it fixes the issue?

**Comment by LocutusOfBorg** [comment]
yes thanks! I'll upload shortly on Debian the fix as long as the copyright one!
cheers!

**Comment by coldfix** [comment]
Ok, great. Merged to master. Let me know, if there is any further issues.
