### ISSUE TITLE
crashes at startup when using config.yml

### ISSUE THREAD

**Issue by frank604** [coldfix/udiskie#84]
Hi again,

I'm having an issue where udiskie crashes when trying to use config.yml (I'm using the default config) which gives a traceback:
```
Traceback (most recent call last):
  File "/usr/bin/udiskie", line 9, in <module>
    load_entry_point('udiskie==1.3.2', 'console_scripts', 'udiskie')()
  File "/usr/lib/python3.5/site-packages/udiskie/cli.py", line 214, in main
    return cls(argv).run()
  File "/usr/lib/python3.5/site-packages/udiskie/cli.py", line 180, in __init__
    config = udiskie.config.Config.from_file(config_file)
  File "/usr/lib/python3.5/site-packages/udiskie/config.py", line 197, in from_file
    return cls.from_file(path)
  File "/usr/lib/python3.5/site-packages/udiskie/config.py", line 215, in from_file
    return cls(load(f))
  File "/usr/lib/python3.5/site-packages/yaml/__init__.py", line 94, in safe_load
    return load(stream, SafeLoader)
  File "/usr/lib/python3.5/site-packages/yaml/__init__.py", line 72, in load
    return loader.get_single_data()
  File "/usr/lib/python3.5/site-packages/yaml/constructor.py", line 35, in get_single_data
    node = self.get_single_node()
  File "/usr/lib/python3.5/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/lib/python3.5/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/lib/python3.5/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python3.5/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/lib/python3.5/site-packages/yaml/composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/usr/lib/python3.5/site-packages/yaml/composer.py", line 110, in compose_sequence_node
    while not self.check_event(SequenceEndEvent):
  File "/usr/lib/python3.5/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/lib/python3.5/site-packages/yaml/parser.py", line 393, in parse_block_sequence_entry
    "expected <block end>, but found %r" % token.id, token.start_mark)
yaml.parser.ParserError: while parsing a block collection
  in "/home/frank604/.config/udiskie/config.yml", line 8, column 5
expected <block end>, but found '?'
  in "/home/frank604/.config/udiskie/config.yml", line 9, column 5

```

Below is my basic config.yml

```
  1 program_options:                                                                    
  2     udisks_version: 2
  3     tray: false
  4     automount: true
  5     notify: true
  6     file_manager: xdg-open
  7 mount_options:
  8     - id_type: exfat
  9     options: [noatime, flush]
```
udiskie works fine when not using the config.yml as well as when I only have lines 1-6 in config.yml.  Thank you for your time.

**Comment by coldfix** [comment]
Hey,

your config file is not valid YAML. Replace the mount options section by:

```
mount_options:
    - id_type: exfat
      options: [noatime, flush]
```

The relative indent of different lines is important, since indent is used as syntax element, as in python.

**Comment by coldfix** [comment]
Oh, sorry, I didn't read that you have only lines 1-6 in your config. Can you please post the exact contents of your config file? `xclip ~/.config/udiskie/config.yml` and then paste here

**Comment by frank604** [comment]
Thank you for looking into this.  
Your indent comment solved it.

I had to add a space or two to the options line.  Thank you so much.  Case closed.
