### ISSUE TITLE
'AutoTray' object has no attribute 'task'

### ISSUE THREAD

**Issue by Stebalien** [coldfix/udiskie#92]
When running `udiskie -s`, I get:

```text
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/udiskie/cli.py", line 262, in _start_async_tasks
    yield self._init()
  File "/usr/lib/python3.5/site-packages/udiskie/cli.py", line 407, in _init
    tasks.append(statusicon.task)
AttributeError: 'AutoTray' object has no attribute 'task'
```

**Comment by coldfix** [comment]
THANKS! Forgot the AutoTray... Bugfix released.

**Comment by Stebalien** [comment]
Thanks.
